title: Leticia da Luz # your name here
logo: "/Foto_perfil/foto_perfil.jpg" # your photo here

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/leticiadluz/">LinkedIn</a> |
  <a href="https://leticiadluz.github.io/">Portfólio</a> |
  <a href="https://github.com/leticiadluz">GitHub</a> |
  <a href="mailto:leticiadluz@gmail.com">E-mail</a>
  </p>
  
  <p align="center">
   Olá, este é o meu portfólio de projetos. <br> 
   Aqui, compartilho como aplico soluções em Dados para resolver problemas de negócios.
   
   </p>
   <p align="center">
   <a href="#inicio">Início</a> <br>
   <a href="#projetos-end-to-end">Projetos de Dados End-to-End</a> <br>
   <a href="#projetos-analise">Projetos de Análise de Dados</a> <br>
   <a href="#projetos-ml">Projetos de Machine Learning</a> <br>
   <a href="#projetos-estatistica">Estatística para Análise de Dados</a> <br>
   <a href="#fundamentos-ed">Fundamentos de Engenharia de Dados</a> <br>
   </p> 
   </p>
   <p align="center">
   <br><br>
   </p>
theme: jekyll-theme-minimal
